# Disable Jekyll and theme processing
theme: null
markdown: kramdown
SCSS:
  compile: false
exclude:
  - .git
  - .gitignore
  - node_modules
  - vendor/bundle
  - .nojekyll
  - assets/css/style.scss
